---
kind: pipeline
type: docker
name: default

platform:
  arch: amd64

steps:
- name: greeting
  image: python:3.10-slim
  commands:
  - pip install -r requirements.txt
  - python -m pip install requests

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: default2

platform:
  arch: amd64

steps:
- name: greeting
  image: python:3.9-slim
  commands:
  - pip install -r requirements.txt
  - python -m pip install requests

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: default3

steps:
- name: greeting
  image: python:3.8-slim
  commands:
  - pip install -r requirements.txt
  - python -m pip install requests

trigger:
  event:
  - pull_request
  action:
  - opened

---
kind: pipeline
type: exec
name: default4

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - cat /etc/os-release

trigger:
  branch:
  - dev