---
kind: pipeline
type: docker
name: default

platform:
  arch: amd64

# Suppressing TOKEN allows the pipeline to execute
# environment:
#   TOKEN:
#     from_secret: Tower_Token
#   DRONE_COMMIT_MESSAGE: ${DRONE_COMMIT_MESSAGE}

steps:
- name: greeting
  image: python:3.10-slim
  environment:
    TOKEN:
      from_secret: Tower_Token
    CRED:
      from_secret: CRED
  commands:
  - ls -al
  - env 
  - pip install httpx
  - apt-get update && apt-get install -y jq
  - credential=$(echo CRED | jq .)
  - echo $credential
  - python3 create_workspace.py \
      --token $TOKEN \
      --wsname $WSNAME \
      --useremail $USEREMAIL \
      --credential $credential

  # - |
  #   if [ $DRONE_COMMIT_MESSAGE = "[CREATE]" ]; then
  #     echo 'Commit message includes [CREATE]'
  #     python3 test_tower_label_limit2.py --action create --token $TOKEN
  #   fi

  # - |
  #   case $DRONE_COMMIT_MESSAGE in
  #     "[CREATE]"* )
  #       python3 test_tower_label_limit2.py --action create --token $TOKEN
  #       ;;
  #     "[DELETE]"* )
  #       python3 test_tower_label_limit2.py --action delete --token $TOKEN
  #       ;;
  #     *) echo "Dont know how to action."
  #   esac

  # Comment out since I only want to manually trigger
  # when:
  #   branch:
  #     - autopopulatews

# https://stackoverflow.com/questions/39577940/drone-io-filter-by-tag-name
# trigger:
#   when:
#     event: tag
#     branch: refs/tags/create*

# ---
# kind: pipeline
# type: docker
# name: labeltest

# platform:
#   arch: amd64

# steps:
# - name: greeting
#   image: python:3.9-slim
#   commands:
#   - pip install httpx
#   - python -m pip install requests

# trigger:
#   branch:
#   - main

# ---
# kind: pipeline
# type: docker
# name: default3

# steps:
# - name: greeting
#   image: python:3.8-slim
#   commands:
#   - pip install -r requirements.txt
#   - python -m pip install requests

# trigger:
#   event:
#   - pull_request
#   action:
#   - opened

# ---
# kind: pipeline
# type: exec
# name: default4

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: greeting
#   commands:
#   - cat /etc/os-release

# trigger:
#   branch:
#   - dev