---
kind: pipeline
type: docker
name: default

platform:
  arch: amd64

# Suppressing TOKEN allows the pipeline to execute
# environment:
#   TOKEN:
#     from_secret: Tower_Token
#   DRONE_COMMIT_MESSAGE: ${DRONE_COMMIT_MESSAGE}

steps:
- name: greeting
  image: python:3.10-slim
  environment:
    TOKEN:
      from_secret: Tower_Token
  commands:
  - pip install httpx
  - ls -al
  - env 
  - echo "${DRONE_COMMIT_MESSAGE}"
  - |
    if [ $DRONE_COMMIT_MESSAGE = "[CREATE]" ]; then
      echo 'Commit message includes [CREATE]'
      python3 test_tower_label_limit2.py --action create --token $TOKEN
    fi
  # - |
  #   if [ $DRONE_COMMIT_MESSAGE = "[DELETE]" ]; then
  #     echo 'Commit message includes [DELETE]'
  #     python3 test_tower_label_limit2.py --action delete --token $TOKEN
  #   fi
  - |
    case $DRONE_COMMIT_MESSAGE in
      "[CREATE]"* )
        python3 test_tower_label_limit2.py --action create --token $TOKEN
        ;;
      "[DELETE]"* )
        python3 test_tower_label_limit2.py --action delete --token $TOKEN
        ;;
      *) echo "Dont know how to action.""
    esac


# https://docs.drone.io/pipeline/environment/substitution/
# yaml: unmarshal errors: cannot unmarshal !!map into string
  # commands:

  # # - export DRONE_COMMIT_MESSAGE="$${DRONE_COMMIT_MESSAGE}""
  # - echo DRONE_COMMIT_MESSAGE is: $${DRONE_COMMIT_MESSAGE}
  # - |
  #   if [ $DRONE_COMMIT_MESSAGE = '[CREATE]' ]; then
  #     echo 'Commit message includes [CREATE]'
  #     python3 test_tower_label_limit2.py --action create --token $TOKEN
  #   fi
  # - |
  #   if [ $DRONE_COMMIT_MESSAGE = '[DELETE]' ]; then
  #     echo 'Commit message includes [DELETE]'
  #     python3 test_tower_label_limit2.py --action delete --token $TOKEN
  #   fi
  
  when:
    branch:
      - labeltest

# https://stackoverflow.com/questions/39577940/drone-io-filter-by-tag-name
# trigger:
#   when:
#     event: tag
#     branch: refs/tags/create*

# ---
# kind: pipeline
# type: docker
# name: labeltest

# platform:
#   arch: amd64

# steps:
# - name: greeting
#   image: python:3.9-slim
#   commands:
#   - pip install httpx
#   - python -m pip install requests

# trigger:
#   branch:
#   - main

# ---
# kind: pipeline
# type: docker
# name: default3

# steps:
# - name: greeting
#   image: python:3.8-slim
#   commands:
#   - pip install -r requirements.txt
#   - python -m pip install requests

# trigger:
#   event:
#   - pull_request
#   action:
#   - opened

# ---
# kind: pipeline
# type: exec
# name: default4

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: greeting
#   commands:
#   - cat /etc/os-release

# trigger:
#   branch:
#   - dev